add exit+calc

diff --git a/laba1/number b/laba1/number
--- a/laba1/number
+++ b/laba1/number
@@ -2,10 +2,10 @@
 number()
 {
 re='^[0-9]+$'
-if ! [[ $1 =~ $re ]] ; then
-echo "Error: $1 not a number" 1>&2
-return 0
-else return 1
+if ! [[ $1 =~ $re ]]
+then echo "Error: $1 not a number" 1>&2
+return 1
+else return 0
 fi
 }
 
